name: "Check"
description: "Check runtime & plugin"
runs:
  using: "composite"
  steps:
    - name: Check
      run: ./gradlew --stacktrace --scan check
      shell: bash
    - name: Publish To Maven Local
      run: ./gradlew --stacktrace --scan publishToMavenLocal
      shell: bash
    - name: Check plugin with JVM JUnit4
      working-directory: tests-projects/tests-jvm-junit4
      run: ../../gradlew --stacktrace --scan check
      shell: bash
    - name: Check plugin with JVM JUnit5
      working-directory: tests-projects/tests-jvm-junit5
      run: ../../gradlew --stacktrace --scan check
      shell: bash
    - name: Check plugin with Android
      working-directory: tests-projects/tests-android
      run: ../../gradlew --stacktrace --scan check
      shell: bash
