name: build and publish a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/*'
      - 'kotlin-*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:
  build-upload:
    runs-on: macOS-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.sonatype_username }}
      SONATYPE_PASSWORD: ${{ secrets.sonatype_password }}
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
      - name: Check
        uses: ./.github/actions/check
      - name: Upload
        run: ./gradlew --stacktrace --scan publishAllPublicationsToOssrhStagingRepository -PgitRef=${{ github.ref }} -Psnapshot=true
        shell: bash
