name: check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'

jobs:

  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        run: ./gradlew --stacktrace check
        shell: bash
      - name: Publish To Maven Local (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew --stacktrace publishToMavenLocal
        shell: bash
      - name: Check plugin with JVM JUnit4 (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        working-directory: tests-projects/tests-jvm-junit4
        run: ../../gradlew --stacktrace check
        shell: bash
      - name: Check plugin with JVM JUnit5 (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        working-directory: tests-projects/tests-jvm-junit5
        run: ../../gradlew --stacktrace check
        shell: bash
      - name: Check plugin with Android old layout (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        working-directory: tests-projects/tests-android-old
        run: ../../gradlew --stacktrace check
        shell: bash
      - name: Check plugin with Android new layout (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        working-directory: tests-projects/tests-android-new
        run: ../../gradlew --stacktrace check
        shell: bash
